site_name: AI on the Edge Device

#site_url: https://example.com/
#site_url: https://jomjol.github.io/AI-on-the-edge-device/index.html
site_url: https://caco3.github.io/AI-on-the-edge-device

repo_url: https://github.com/jomjol/AI-on-the-edge-device

#edit_uri:

theme: readthedocs
#  features:
#    - navigation.sections

favicon: watermeter.svg


plugins:
    - search
    - awesome-pages


# The navigation is configured in the .pages file!